char *IPproto[] = {"HOPOPT",     "ICMP",      "IGMP",        "GGP",
                   "IPv4",       "ST",        "TCP",         "CBT",
                   "EGP",        "IGP",       "BBN-RCC-MON", "NVP-II",
                   "PUP",        "ARGUS",     "EMCON",       "XNET",
                   "CHAOS",      "UDP",       "MUX",         "DCN-MEAS",
                   "HMP",        "PRM",       "XNS-IDP",     "TRUNK-1",
                   "TRUNK-2",    "LEAF-1",    "LEAF-2",      "RDP",
                   "IRTP",       "ISO-TP4",   "NETBLT",      "MFE-NSP",
                   "MERIT-INP",  "DCCP",      "3PC",         "IDPR",
                   "XTP",        "DDP",       "IDPR-CMTP",   "TP++",
                   "IL",         "IPv6",      "SDRP",        "IPv6-Route",
                   "IPv6-Frag",  "IDRP",      "RSVP",        "GRE",
                   "DSR",        "BNA",       "ESP",         "AH",
                   "I-NLSP",     "SWIPE",     "NARP",        "MOBILE",
                   "TLSP",       "SKIP",      "IPv6-ICMP",   "IPv6-NoNxt",
                   "IPv6-Opts",  "61",        "CFTP",        "63",
                   "SAT-EXPAK",  "KRYPTOLAN", "RVD",         "IPPC",
                   "68",         "SAT-MON",   "VISA",        "IPCV",
                   "CPNX",       "CPHB",      "WSN",         "PVP",
                   "BR-SAT-MON", "SUN-ND",    "WB-MON",      "WB-EXPAK",
                   "ISO-IP",     "VMTP",      "SECURE-VMTP", "VINES",
                   "TTP",        "IPTM",      "NSFNET-IGP",  "DGP",
                   "TCF",        "EIGRP",     "OSPFIGP",     "Sprite-RPC",
                   "LARP",       "MTP",       "AX.25",       "IPIP",
                   "MICP",       "SCC-SP",    "ETHERIP",     "ENCAP",
                   "99",         "GMTP",      "IFMP",        "PNNI",
                   "PIM",        "ARIS",      "SCPS",        "QNX",
                   "A/N",        "IPComp",    "SNP",         "Compaq-Peer",
                   "IPX-in-IP",  "VRRP",      "PGM",         "114",
                   "L2TP",       "DDX",       "IATP",        "STP",
                   "SRP",        "UTI",       "SMP",         "SM",
                   "PTP",        "ISIS",      "FIRE",        "CRTP",
                   "CRUDP",      "SSCOPMCE",  "IPLT",        "SPS",
                   "PIPE",       "SCTP",      "FC",          "RSVP-E2E-IGNORE",
                   "Mobility",   "UDPLite",   "MPLS-in-IP",  "manet",
                   "HIP",        "Shim6",     "WESP",        "ROHC",
                   "Ethernet",   "253",       "254",         "Reserved",
                   NULL};

char *ARPproto[] = {"Reserved",
                    "REQUEST",
                    "REPLY",
                    "request Reverse",
                    "reply Reverse",
                    "DRARP-Request",
                    "DRARP-Reply",
                    "DRARP-Error",
                    "InARP-Request",
                    "InARP-Reply",
                    "ARP-NAK",
                    "MARS-Request",
                    "MARS-Multi",
                    "MARS-MServ",
                    "MARS-Join",
                    "MARS-Leave",
                    "MARS-NAK",
                    "MARS-Unserv",
                    "MARS-SJoin",
                    "MARS-SLeave",
                    "MARS-Grouplist-Request",
                    "MARS-Grouplist-Reply",
                    "MARS-Redirect-Map",
                    "MAPOS-UNARP",
                    "OP_EXP1",
                    "OP_EXP2"};

struct ethernet_protocols {
    char *name;
    unsigned int proto;
} ETHproto[] = {
    {"LOOP", 0x0060},     {"PUP", 0x0200},        {"PUPAT", 0x0201},
    {"TSN", 0x22F0},      {"ERSPAN2", 0x22EB},    {"IP", 0x0800},
    {"X25", 0x0805},      {"ARP", 0x0806},        {"BPQ", 0x08FF},
    {"IEEEPUP", 0x0a00},  {"IEEEPUPAT", 0x0a01},  {"BATMAN", 0x4305},
    {"DEC", 0x6000},      {"DNA_DL", 0x6001},     {"DNA_RC", 0x6002},
    {"DNA_RT", 0x6003},   {"LAT", 0x6004},        {"DIAG", 0x6005},
    {"CUST", 0x6006},     {"SCA", 0x6007},        {"TEB", 0x6558},
    {"RARP", 0x8035},     {"ATALK", 0x809B},      {"AARP", 0x80F3},
    {"8021Q", 0x8100},    {"ERSPAN", 0x88BE},     {"IPX", 0x8137},
    {"IPV6", 0x86DD},     {"PAUSE", 0x8808},      {"SLOW", 0x8809},
    {"WCCP", 0x883E},     {"MPLS_UC", 0x8847},    {"MPLS_MC", 0x8848},
    {"ATMMPOA", 0x884c},  {"PPP_DISC", 0x8863},   {"PPP_SES", 0x8864},
    {"LINK_CTL", 0x886c}, {"ATMFATE", 0x8884},    {"PAE", 0x888E},
    {"REALTEK", 0x8899},  {"AOE", 0x88A2},        {"8021AD", 0x88A8},
    {"EX1", 0x88B5},      {"PREAUTH", 0x88C7},    {"TIPC", 0x88CA},
    {"LLDP", 0x88CC},     {"MRP", 0x88E3},        {"MACSEC", 0x88E5},
    {"8021AH", 0x88E7},   {"MVRP", 0x88F5},       {"NCSI", 0x88F8},
    {"PRP", 0x88FB},      {"CFM", 0x8902},        {"FCOE", 0x8906},
    {"IBOE", 0x8915},     {"TDLS", 0x890D},       {"FIP", 0x8914},
    {"HSR", 0x892F},      {"NSH", 0x894F},        {"LOOPBACK", 0x9000},
    {"QINQ1", 0x9100},    {"QINQ2", 0x9200},      {"QINQ3", 0x9300},
    {"EDSA", 0xDADA},     {"DSA_8021Q", 0xDADB},  {"IFE", 0xED3E},
    {"AF_IUCV", 0xFBFB},  {"MIN", 0x0600},        {"AX25", 0x0002},
    {"ALL", 0x0003},      {"SNAP", 0x0005},       {"DDCMP", 0x0006},
    {"WAN_PPP", 0x0007},  {"PPP_MP", 0x0008},     {"LOCALTALK", 0x0009},
    {"CAN", 0x000C},      {"CANFD", 0x000D},      {"PPPTALK", 0x0010},
    {"TR_802_2", 0x0011}, {"MOBITEX", 0x0015},    {"CONTROL", 0x0016},
    {"IRDA", 0x0017},     {"ECONET", 0x0018},     {"HDLC", 0x0019},
    {"ARCNET", 0x001A},   {"DSA", 0x001B},        {"TRAILER", 0x001C},
    {"PHONET", 0x00F5},   {"IEEE802154", 0x00F6}, {"CAIF", 0x00F7},
    {"XDSA", 0x00F8},     {"MCTP", 0x00FA},       {NULL, 0}};

#define MAXETHPROTONAME 20

char *get_op(int op) {
    if (op > sizeof(ARPproto) / sizeof(ARPproto[0]))
      return "UNRECOGNISED";
    else
        return ARPproto[op];
}
